### ISSUE TITLE
Excercise Bug: 08-Bootstrap-Forms

### ISSUE THREAD

**Issue by akers2534** [learnpack/learnpack#1261]
Describe the bug: checkbox test not passing even though code was copied from bootstrap and it looks the same.
https://gitpod.io#snapshot/eaf5f228-861d-4213-bafe-d3c62a5962e6

**1. Exercise Name:** 08-Bootstrap-Forms

**2. Repository URL:** https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial

**Comment by UmiKami** [comment]
Your test is not passing because you have a typo in the word Remember.

![Image](https://user-images.githubusercontent.com/60261375/214978677-6a01ce7b-ed5e-4a6b-9c8c-7a1fabb7f151.png)

Remember, when a test fails, it tells you exactly what's failing. If you check the results of the tests, the only one that is failing is the following one: 
`x (fail) 10. The checkbox should have a side text "Remember me"`

In your case it was a typo. You wrote `Remeber me`, instead of `Remember me`

**Comment by UmiKami** [comment]
No issues were found.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.20</hrs>
