### ISSUE TITLE
Excercise Bug: 12.1-body-content

### ISSUE THREAD

**Issue by jserrano113** [learnpack/learnpack#1304]
Describe the bug:

**1. Exercise Name:** 12.1-body-content

**2. Repository URL:** https://github.com/breatheco-de/exercise-postcard

When I test my code it says everything is fine but it's not allowing me to build it.

**Comment by UmiKami** [comment]
Tested it. Cannot replicate. It might not build because you might have a syntax error in your HTML. Remember, the tests only check that you have the necessary stuff. They do not check for syntax errors in your code. You can validate your HTML code here:

https://validator.w3.org/#validate_by_input

It should tell you if you have any errors in your code

**Comment by UmiKami** [comment]
no changes made

**Comment by UmiKami** [comment]
Hrs: <hrs>0.10</hrs>
