### ISSUE TITLE
Excercise Bug: 10-Remove-vowels

### ISSUE THREAD

**Issue by celes-sb** [learnpack/learnpack#1305]
Describe the bug:

**1. Exercise Name:** 10-Remove-vowels
**2. Repository URL:** https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial

The exercise is already 99% done (the only thing missing in the code is a `.toUpperCase()` ) so there is no chance for the student to start from zero. Even when clicking on "reset". It doesn't reset the whole thing.

**Comment by tommygonzaleza** [comment]
Propose some changes on this exercise to make it more challenging @UmiKami

**Comment by UmiKami** [comment]
Changes made: Removed the function that was there by default. The requester had already made a pull request, which removed most of the stuff already done.

To make it even more challenging, I changed the last test to check for the function return rather than the console log. This way, we can test the function with multiple inputs and make sure the user is not just console-logging the answer.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/87
Hrs: <hrs>0.35</hrs>
