### ISSUE TITLE
El test del ejercicio 09.1 del prework de DS no pasa si uso funciones

### ISSUE THREAD

**Issue by marcogonzalo** [learnpack/learnpack#1315]
ejercicio 09.1 pythonlist:
09.1 Minimum integer:

El test falla si se hace como funciones, pero no si se hace imperativo. Se hizo con funciones porque en los anteriores ya se venía pidiendo hacer funciones, por lo que creo que es importante permitirlo

**Comment by UmiKami** [comment]
cambie el test y las instructions para que se use una funcion la cual retorna el valor minimo de una lista.

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/99
Hrs: <hrs>0.48</hrs>

**Comment by UmiKami** [comment]
New test case:

```python
@pytest.mark.it("The function should print the minimum number from my_list")
def test_printed_output(capsys, app):
    def minInteger_wrapper(my_list):
        result = app.minInteger(my_list)
        print(result)
        return result

    original_minInteger = app.minInteger
    app.minInteger = minInteger_wrapper

    exec(open(app.__file__).read())
    captured = capsys.readouterr()

    app.minInteger = original_minInteger

    assert int(captured.out.strip()) == min(app.my_list)
```

Explanation:

1. It defines a minInteger_wrapper function that calls the original minInteger function, prints the result, and returns it.
2. It temporarily replaces the minInteger function in the app module with the wrapper function.
3. It re-executes the app.py file, which now calls the wrapper function instead of the original minInteger function, and thus captures the printed output.
4. It restores the original minInteger function in the app module.
5. It checks if the captured output matches the minimum value in my_list.
