### ISSUE TITLE
test inconsistente en practica de css

### ISSUE THREAD

**Issue by josemoracard** [learnpack/learnpack#1375]
Hay un test que se repite en casi todos los ejercicios:
"You should not change the existing head tag elements"

Este test aveces funciona bien, aveces funciona mal. Es inconsistente

ejemplos en estos ejercicios
01.2 Your First Style y 01.3 Your Second Style
si borro <style> y <head> el test sigue dando correcto, cuando debería dar incorrecto al borrar <style>

en el ejercicio
02 Separate Stylesheet
parece que todo va bien, si borro <link> el test sale incorrecto, pero si borro solamente <head> el test da correcto

esto pasa en mas ejercicios

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
Checking for the style tag in 1.2 and 1.3 is redundant since the test will fail if the user does not style the elements anyway. Even if the head test passes, the main test, the one that checks for the styling, does not, and that's the purpose of these exercises. 

In exercise 2, if you remove the link tag, it will give you an error because it is necessary to apply the style. 

In any case, modifications of the head tag are not the purpose of these exercises. We just check exactly what's necessary to meet the goal of the assignment.

**Comment by UmiKami** [comment]
Nothing needs to change from my POV.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.17</hrs>
