### ISSUE TITLE
Review Numpy exercises' tests

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1407]
These exercises' tests are not passing if you don't delete the content of the last exercise. Please allow all the test to work even if you have extra content in the entry file.

Also check for possible improvements

Repository: https://github.com/breatheco-de/numpy-tutorial-exercises

**Comment by UmiKami** [comment]
First five exercises:
2. added solution file for 002
3. added solution file and made regex more flexible towards spaces
4. added solution and test to prevent hard-coded solution
5. added solution, fixed/improve 2 tests, added hardcode check

**Comment by UmiKami** [comment]
PR: https://github.com/breatheco-de/numpy-tutorial-exercises/pull/5
Hrs: <hrs>0.37</hrs>

**Comment by UmiKami** [comment]
3/ made test more flexible since numpy version can be changed in the future
6/ added test to verify we are checking for add function '
7/ made test flexible when checking caputured out | added hardcode check
8/ same as previous exercise
9/ same as previous exercise | test that checks for reverse operation made more flexible
10/ made test flexible when checking caputured out | added hardcode check
11/ same as previous exercise || checked array is being used
12/ same as previous exercise
13/ changed function exist test to use regex and be more flexible

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/numpy-tutorial-exercises/pull/1
Hrs: <hrs> 1.88 </hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1.68</hrs>
