### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by alegonfern** [learnpack/learnpack#1408]
Describe the bug: The exercise does not recognize the command:
table tr:nth-child(odd) {
background-color: yellow;
}

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
Two issues were found.

**First issue:**

The test is not looking for the selector `table tr:nth-child` hence it fails since it cannot find the selector and its required values

**Solution**: Modify test to look for selector that contains `tr:nth-child`


**Second issue:**

The same test that was failing on issue 1, was failing when background-color: yellow because background property was not defined when background-color is defined. More specifically background.toLowerCase() was causing the issue.


**Solution**: Added ternary check to existing conditional

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/125
Hrs: <hrs>0.20</hrs>
