### ISSUE TITLE
Mejorar tutorial de Python Beginner

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#1422]
Agregar mejoras al tutorial:
- Agregar solution.hide.py
- Mejorar las intrucciones de cada ejercicio
- Mejorar los tests para que no sean muy especificos pero si restringan de errores o hard code

Repository: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/

**Comment by UmiKami** [comment]
- 01 | Modified instructions to be more accurate > every programming language has a console but not every LANGUAGE has a console. For example, many markup languages (HTML, XML, etc.), stylesheet languages (CSS), and database languages (SQL) do not have consoles, but they are used in environments (like web browsers, text editors, or database management systems) that provide other ways of interaction. | Made test more flexible @0.14
- 02 | Provided additional, more extensive analogy as to what a variable is.| made test more flexible @0.22
- 03 | Made test more flexible | clarified instructions by adding quotes to wanted value so that beginners do not get confused@0.12 
- 04 | Made tests more flexible | fixed typo on instructions @0.13
- 05 | Made tests more flexible | instructions are straightforward @0.12
- 06 | Made tests more flexible | added note of common mistake to keep an eye out for
- 07 | Made tests more flexible
- 08.1 | Made tests more flexible
- 08.2 | Made tests more flexible 
- 09 | Made tests more flexible

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/86
Hrs: <hrs> 0.96</hrs>

**Comment by tommygonzaleza** [comment]
Agregue un review al PR

**Comment by UmiKami** [comment]
Rev 1:

- 02 | Added resource on what strings are and how they work, enhanced analogy on what variables are @0.17
- 03 | Reversed the first test to the original @0.07
- 04 | Reverted to `in` operator @0.02
- 06 | Added extra documentation on string concatenation, enhanced explanation on what concatenation is and provided an analogy, made tests 3 and 4 stricter in terms of equality but made them case insensitive @0.65
- 07 | On test 2, assertion returned to strict equality @0.02
- 8.1| Added hint table of relational operators to help students decide a condition for their if/else statements  @0.27
- 8.2| Expanded on instruction steps, added clarifying note under data table. Provided visual cues for people who don't understand English on the app.py @0.38
- 09 | added visual cues, added hints, and enhanced explanation of `randint `@0.25
- 10 | added visual cues, fixed test that was not running because it shared the same function name, added solution file, added hints @0.22
- 10.1 |   added visual cues, fixed test that was not running because it shared the same function name, added solution file @0.10
- 11 | added visual cues, fixed typos / inconsistencies in the explanations, added test to check if user uses print, and added clarity to instructions @0.17
- 12 | added visual cues, made test more flexible @0.10
- 13 | enhanced instructions by adding clarity and added visual cues @0.07
- 14 | Made test more flexible, added additional docs @0.08
- 15 | added visual cues, added string check flexibility @0.04

**Comment by UmiKami** [comment]
Rev 2:

- 08.2 / 09 / 10 / 10.1 / 11 / 12 / 13 | Replaced arrow with a visible, more universal one ( ↓  ⬆) @0.17
- 02 | added visual cues to keep consistency @0.02
- 03 | added visual cues to keep consistency @0.02
- 04 |  added visual cues to keep consistency @0.02
- 05 |  added visual cues to keep consistency @0.02
- 06 |  added visual cues to keep consistency @0.02
- 07 |  added visual cues to keep consistency @0.02
- 08.1 | added visual cues @0.02
- 08.2 | added visual cues to solution file @0.02
- 09 | added visual cues to solution file @0.02
- 11 | added visual cues to solution file @0.02
- 12 | added visual cues to solution file @0.02
- 13 | added visual cues to solution file and removed partial answer from app.py @0.03
- 15 | added visual cues to solution file @0.02
- 16 | added visual cues, added small translation to es.md file, added solution file @0.28
- 17 | added visual cues, translated onomatopoeia in readme for English speakers, added clarity to steps in instructions @0.30
- 18 | added visual cues, added resources to refresh the student's mind @0.23
- 19 | added visual cues, exercise had already been enhanced previously so couldn't find but a typo in the readme @0.13
- 01 | added hint on how to execute code in learnpack, included screenshot @0.07

**Comment by UmiKami** [comment]
PR: https://github.com/4GeeksAcademy/python-beginner-programming-exercises/pull/86
Hrs: <hrs>5</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>
