### ISSUE TITLE
Excercise Bug: 08.2-How-Much-The-Wedding-Costs

### ISSUE THREAD

**Issue by paulaechemendia** [learnpack/learnpack#1462]
Describe the bug:
I am getting the correct result but it is saying it is wong because it prints 4000 instead of 4,000. However, it does not understand 4,000 as a number 

**1. Exercise Name:** 08.2-How-Much-The-Wedding-Costs

**2. Repository URL:** https://github.com/4GeeksAcademy/python-beginner-programming-exercises

**Comment by UmiKami** [comment]
None of the tests are expecting "4,000", tests are expecting 4000 as an integer. 

```js
user_input = int(input('How many people are coming to your wedding?\n'))

# ❌ ⬆ DON'T CHANGE THE CODE ABOVE  ⬆ ❌

if user_input <= 50:
    price = 4000
# ✅ ↓ Your code here ↓ ✅
elif user_input <= 100:
    price = 10000
elif user_input <= 200:
    price = 15000
else:
    price = 20000

# ❌ ↓ DON'T CHANGE THE CODE BELOW ↓ ❌
print('Your wedding will cost '+str(price)+' dollars')
```

Observe the above solution. That solution passes with all tests. I would need more details as to what error you are getting.

Do note, some fixes to this exercise were applied a few minutes ago, so it may be worthwhile to check on it again and compare your solution to the one I gave you above since I was not able to replicate your issue.

**Comment by UmiKami** [comment]
Hrs: <hrs>0.08</hrs>
