### ISSUE TITLE
Excercise Bug: 03-first-flask-app

### ISSUE THREAD

**Issue by Justice3001** [learnpack/learnpack#1506]
Describe the bug:

**1. Exercise Name:** 03-first-flask-app

**2. Repository URL:** https://github.com/breatheco-de/python-flask-api-tutorial

https://github.com/learnpack/learnpack/assets/112534103/719285c8-b682-42dc-a04f-cd12146e941c

https://github.com/learnpack/learnpack/assets/112534103/60d62367-f279-4cb3-ac64-7d605f9ce1e4

![6](https://github.com/learnpack/learnpack/assets/112534103/a2b84006-5287-4620-8380-4c9c0fa58926)

https://github.com/learnpack/learnpack/assets/112534103/6e72746a-4205-4c39-9e5d-308e3f06b807

![4](https://github.com/learnpack/learnpack/assets/112534103/11bd3c2f-2853-4d85-911d-80176fd5918a)
![3](https://github.com/learnpack/learnpack/assets/112534103/dd2aac4c-070e-41ae-b04d-496e549d5e63)
![2](https://github.com/learnpack/learnpack/assets/112534103/0745d65e-3570-4785-a486-e668a14b0b8b)
![1](https://github.com/learnpack/learnpack/assets/112534103/21e05bcf-aa3c-4b48-927b-9e2fa319bb4f)

did everything right still not working.

**Comment by AnggieAlava** [comment]
Ok, I checked the exercise test and also the flask and python 3 installations with pipenv are _working correctly_. What I can notice is an **`error when locating the src folder and its file app.py`** in the `root directory`. As you show in the last message, in the picture, `your src folder is inside the .env folder`, that's why the` error that shows the console in red is an indication that the src must exist`, because when running the test, `learnpack is not finding the src => app.py`. Here is a picture of what your directory should look like, so that the test finds the src folder and the app.py file. @Justice3001 

![Image](https://github.com/learnpack/learnpack/assets/131820456/f9c6d6fb-d0ad-4190-b887-b81298c0222f)
