### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by ColbyWTaylor** [learnpack/learnpack#384]
1.Exercise Name: 03-Print-variables-in-the-console

2.Repository URL: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

If the previous lines are removed it fails the test, even when what is asked is present

**Comment by kiddopro** [comment]
The problem was that the test expect the console.log to run twice, once for the previous line (mySuperVariable) and once for the color. So when you delete or comment out console.log for mySuperVariable the test does not pass even though the console.log for the color is there.
PR: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/36
Hrs: <hrs>0.06</hrs>
