### ISSUE TITLE
Not accepting my code due to a space after key

### ISSUE THREAD

**Issue by barcelonabrian11** [learnpack/learnpack#385]
1.Exercise Name: 02.1-maping-array-objects-to-li

2.Repository URL: https://github.com/4GeeksAcademy/react-tutorial-exercises
![image](https://user-images.githubusercontent.com/88598302/134158412-df4d7a90-9ccf-43a6-9ce2-b6ddc4ac1d91.png)

**Comment by kiddopro** [comment]
https://github.com/4GeeksAcademy/react-tutorial-exercises/compare/master...kiddopro:02.1-maping-array-objects-to-li?expand=1
The issue was that the test was strictly to be key={i} with no spaces in between so adding spaces causes the test to fail even if you type key={ i } or key ={i}. To solve this I added a regex statement to allow empty spaces.
PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/79
Hrs: <hrs>0.5</hrs>

**Comment by tommygonzaleza** [comment]
Fix this test as well in order to avoid the spaces error with this one too.

```js
test("You should use singleAnimal to get the anima for each of the iterations", () => {
    expect(app_content).toMatch("{singleAnimal.label}");
})
```

**Comment by tommygonzaleza** [comment]
Remember to run `learnpack clean` before staging your changes to Github

**Comment by kiddopro** [comment]
Done
