### ISSUE TITLE
Excercise Bug

### ISSUE THREAD

**Issue by willy5360** [learnpack/learnpack#396]
1.Exercise Name: 22-Russian-Roulette

2.Repository URL: https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial

I was doing this excercise for a long time, then I notice that the test results goes from "everything as expected" to "not working". without changing the code.  So I might have resolved the exercise long time ago, but it was the test, which have been failing and making me feel that I was wrong.

![image](https://user-images.githubusercontent.com/84270420/135665002-8f9c491a-6039-44f1-ac5b-47c05e314d60.png)
![image](https://user-images.githubusercontent.com/84270420/135665063-b893ac74-1185-4758-9c94-a55f575f8f6b.png)

**Comment by tommygonzaleza** [comment]
Hello @willy5360 ! It looks like the problem is with your code.

On the condition, instead of having `spinnerPosition = (spinChamber()===4)`, you should have something like:: `spinnerPosition == bulletPosition`

And then on when you call the function, should pass as parameter `spinChamber()` in that way, spinnerPosition will have a value
