### ISSUE TITLE
Add tests to learnpack audit

### ISSUE THREAD

**Issue by alesanchezr** [learnpack/learnpack#432]
- [x] Check that all readme's have content inside.
- [x] Warn if there are files in the exercises folder that are not within any "./exercise"
- [x] It will be nice to know how many files/images/etc were reviewed on the final report, for example:

Building the exercise index...
ⓘ Checking if the config file is fine... `ok`.
ⓘ Checking if the images are working... `24 images ok`.
ⓘ Checking if important files are missing... (gitignore...)
ⓘ Checking exercises (README's, translations)... `34 exercises ok`.
✓ We didn't find any errors in this repository `among 23 excises, 12 images, 34 links and bla bla`.

**Comment by tommygonzaleza** [comment]
Is it okay if the message that it is showing in the last task looks like this:
![image](https://user-images.githubusercontent.com/56565994/137215797-31741e17-2758-4e5b-974d-b088ccd2e3f6.png)

Because I don't know how to add it on the same line as it is printing the messages in different moments. Or do you prefer to print both at the same time?

**Comment by tommygonzaleza** [comment]
PR: https://github.com/learnpack/learnpack-cli/pull/15
Hrs: <hrs>2.35</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>2.35</hrs>
