### ISSUE TITLE
Review the exercise: 159.3 - Fashion Inventory C

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#649]
Exercise: 159.3-FashionInventory-C and 159.4-FashionInventory-D

Repository: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/

This exercise is so confusing, review the exercise file, test and readmes

**Comment by tommygonzaleza** [comment]
Review the READMEs, tests, and app.js file.

**Comment by kiddopro** [comment]
The problem is that there was little assistance to the student according to what he had to do. In exercise 159.3 the tests expected there to be another function other than the one in the app.js file but it did not say in the instructions to create this function. The test also did not expect the function found in app.js to exist.

PR: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/87

**Comment by kiddopro** [comment]
Hrs: <hrs>1</hrs>

**Comment by kiddopro** [comment]
Hrs: <hrs>1.0833</hrs>

**Comment by tommygonzaleza** [comment]
Please add the following changes:

- [ ] 159.3-FashionInventory-C/test.js Check the function with different input. Also, check that the function returns something
- [ ] 159.4-FashionInventory-C change both readmes to the correct structure.
- [ ] 159.4-FashionInventory-C: The test should check that the function returns something. Then it should check that it workss with two different inputs.

**Comment by kiddopro** [comment]
Hrs: <hrs>1.24996666667</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1.25</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1.25</hrs>
