### ISSUE TITLE
Exercise Bug: 03.2-a-real-component

### ISSUE THREAD

**Issue by tommygonzaleza** [learnpack/learnpack#665]
Exercise: 03.2-a-real-component

Repository: https://github.com/4GeeksAcademy/react-tutorial-exercises

Description: The instructions are giving an image source but the test is expecting a different one.

![image](https://user-images.githubusercontent.com/56565994/151449278-fb475014-7836-4c39-9752-569c9d9e97c0.png)

**Comment by kiddopro** [comment]
I just reviewed the test and basically the problem was the readme because it asked for a function or component called "Card" when it was tested by "BoostrapCard".

Another thing that I found odd was that in the screenshot you uploaded, the src of the image looks cut off (.../...) when I see the full url.

//attach image
![image](https://user-images.githubusercontent.com/82285542/151456429-138ebbbc-8714-49a9-b0af-ea555617be21.png)


PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/83

**Comment by kiddopro** [comment]
Hrs: <hrs>0.25</hrs>

**Comment by tommygonzaleza** [comment]
You have to pull the code from the main repository's master branch, and then fix the issue that I showed you before.

**Comment by kiddopro** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by alesanchezr** [comment]
Hrs: <hrs>0.33</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>0.33</hrs>
